### ISSUE TITLE
What could go wrong if not using uppercase in route names? 

### ISSUE THREAD

**Issue by ddanielcruzz** [fenok/react-router-typesafe-routes#46]
Hey, great library! 

I saw the in the docs that mention the following: 

> ❗Child routes have to start with an uppercase letter to prevent overlapping with route API.

I was wondering if you could go more in detail of what this means, as I like my routes in lowercase haha. 

Thanks!

**Comment by fenok** [comment]
Hi, thanks!

I wanted to ensure that the future route APIs wouldn't clash with someone's child routes. Using an uppercase letter also clearly indicates that it's a child route.

I've actually come to regret the decision to force child routes to start with an uppercase letter. The next major release will allow basically any naming scheme for child routes because route APIs will be prefixed with a `$` (at least it's the current plan). It's like 90% done, I just need to refactor the code a bit and document everything.

**Comment by fenok** [comment]
V2 is released, route names can start with a lowercase letter now.
