### ISSUE TITLE
v6 uninline child

### ISSUE THREAD

**Issue by thejuan** [fenok/react-router-typesafe-routes#9]
Playing with the v6 branch.
It'd be nice if you could something like

const detailsRoutes = PRODUCT.DETAILS.uninline(PRODUCT).

So you could then use inline children to get the easy dot notation access, but break it apart when creating routes.

**Comment by thejuan** [comment]
Or even

const details = useRelativeRoutes(PRODUCT.DETAILS) and it uses current location information to break it apart.

**Comment by fenok** [comment]
Hello and thanks for your interest in the library!

I thought about providing a way to extract/uninline a child route, but eventually, I settled on the idea that it should be done during routes definition:

```typescript
const DETAILS = route("details");

const PRODUCT = route("product/:id", {}, { DETAILS });

const ROUTE_PARTS = {
  DETAILS
}

const ROUTES = {
  PRODUCT
}
```

This way, we explicitly allow `DETAILS` to be used independently, and we can also use `PRODUCT.DETAILS`. 

What I considered:

- Providing a field with the original route, say `PRODUCT.DETAILS.uninline === DETAILS`. Dismissed as an API overcomplication, because it's easy to extract the route beforehand and get the same result.
- Providing `originalPath` and `originalRelativePath` fields (only for using in a `<Route />` `path` prop!), e.g. `PRODUCT.DETAILS.originalPath === '/details'` and `PRODUCT.DETAILS.originalRelativePath === 'details'`. Dismissed as an API overcomplication, because there are already `path` and `relativePath` fields, and the combination of these fileds would be extremely confusing. It's also _safer_ to pass an entire absolute path to the `path` prop, because this way it's impossible to create an unexpected path (in case of `<Route/>` nesting). However, there _are_ edge cases when you do need to extract children, as written in the README.

Regarding your suggestions:
- `const details = useRelativeRoutes(PRODUCT.DETAILS)` can't be statically typed, because it uses current location information, so it's most likely a no-go.
- `const detailsRoutes = PRODUCT.DETAILS.uninline(PRODUCT)` - do I understand correctly that it's basically the same as my `PRODUCT.DETAILS.uninline`, but you can specify which part to drop? Like `PRODUCT.DETAILS.SUB_DETAILS.uninline(PRODUCT) === DETAILS.SUB_DETAILS`? If so, you can extract children beforehand, as I mentioned earlier, and get basically the same result. Note that you most likely don't need extracted children when you define your `<Route/>`s, and when you build URLs, it's also safer to stick to absolute URLs.

Please let me know if I misunderstood something.

**Comment by thejuan** [comment]
Our use case is mainly to allow relative `Navigate` to redirect default paths without having to know parameters to use `.buildPath` inside a `Routes`
I have currently written a helper to do it `relativeFrom`
Maybe there is a better way to achieve this?

```
  <Route path={roleLocations.Definition.Instance.path} element={<RoleDefinitionWizard />}>
                  <Route path={Basics.path} element={<RoleBasicsView />}>
                    <Route path={Basics.Title.path} element={<RoleBasicsTitleView />} />
                   ...
                    <Route path="" element={<Navigate replace to={relativeFrom(Basics, Basics.Title)} />} />
                  </Route>
```

**Comment by fenok** [comment]
Oh, now I understand what you want. Unfortunately, at the moment the only way to achieve that is to extract the child route beforehand and call `.buildRelativeUrl()` (or `.buildRelativePath()`) on it.

It would look like this:
```javascript jsx
<Route path={roleLocations.Definition.Instance.path} element={<RoleDefinitionWizard />}>
  <Route path={roleLocations.Definition.Instance.Basics.path} element={<RoleBasicsView />}>
    <Route path={roleLocations.Definition.Instance.Basics.Title.path} element={<RoleBasicsTitleView />} />
    <Route index element={<Navigate replace to={Title.buildRelativeUrl({})} />} />
  </Route>
</Route>
```
Note that, in your snippet, `Basics` has to be equal to `roleLocations.Definition.Instance.Basics` (because you use absolute `.path` field), so I just wrote it explicitly. I also used `index` instead of `path=""`, because, AFAIK, it's the intended way to define such routes.

I would advise against using `relativeFrom`, because it's not type-safe (what if `Title` had a path parameter?).

> Defining everything as un-inlined looses alot of meaning

I totally agree! I thought that uninlining child routes is a relatively rare use-case, but now I see that I might be wrong. I can't think of a convenient and comprehensive API for this, though.

Sorry for the late response 😅

**Comment by fenok** [comment]
I mean, `PRODUCT.DETAILS.SUB_DETAILS.WHATEVER.uninline(PRODUCT.DETAILS) === SUB_DETAILS.WHATEVER` is comprehensive and probably doable, but is it really convenient?

**Comment by fenok** [comment]
Ok, I think I got this. I published a new version under `next` tag which includes API for children uninlining. It can be used like this:

```javascript
<Route path={roleLocations.Definition.Instance.path} element={<RoleDefinitionWizard />}>
  <Route path={roleLocations.Definition.Instance.Basics.path} element={<RoleBasicsView />}>
    <Route path={roleLocations.Definition.Instance.Basics.Title.path} element={<RoleBasicsTitleView />} />
    <Route index element={<Navigate replace to={roleLocations.Definition.Instance.Basics.$.Title.buildRelativeUrl({})} />} />
  </Route>
</Route>
```

The mental model here is that `$` cuts everything at the left side, and we get just `Title` as if it was uninlined.

Internally, `$` just contains original child routes, so it was very easy to implement 😅

**Comment by thejuan** [comment]
Amazing! Thankyou
